/*
 * Translator Knowledge Beacon API
 * This is the Translator Knowledge Beacon web service application programming interface (API).  This OpenAPI (\"Swagger\") document may be used as the input specification into a tool like [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen/blob/master/README.md) to generate client and server code stubs implementing the API, in any one of several supported computer languages and frameworks. In order to customize usage to your web site, you should change the 'host' directive below to your hostname. 
 *
 * OpenAPI spec version: 1.0.11
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.api;

import java.util.List;

import org.junit.Ignore;
//import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import bio.knowledge.client.ApiException;
import bio.knowledge.client.model.BeaconConcept;
import bio.knowledge.client.model.BeaconConceptWithDetails;

/**
 * API tests for ConceptsApi - data taken from the Reference Beacon SemMedDb data
 */
@Ignore
public class ConceptsApiTest {
	
	private static Logger _logger = LoggerFactory.getLogger(ConceptsApiTest.class);
	
    private final ConceptsApi api = new ConceptsApi();
    
    /**
     * 
     *
     * Retrieves details for a specified concepts in the system, as specified by a (url-encoded) CURIE identifier of a concept known the given knowledge source. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBeaconConceptWithDetailsTest() throws ApiException {
    	
    		_logger.debug("getBeaconConceptWithDetailsTest, with wd:Q18250517");
    		
        String conceptId = "wd:Q18250517";
        List<BeaconConceptWithDetails> response = api.getConceptDetails(conceptId);
        
        assert(response.size()>0);

        for(BeaconConceptWithDetails concept : response) {
        		_logger.debug("Test concept:"+concept.toString());
        }
    }
    
    /**
     * 
     *
     * Retrieves a (paged) list of concepts in the system 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConceptsTest() throws ApiException {
    	
    		_logger.debug("getConceptsTest, with keyword 'BRCA':");
    	
        String keywords = "BRCA";
        String types = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        
        try {
	        List<BeaconConcept> response = api.getConcepts(keywords, types, pageNumber, pageSize);
	
	        assert(response.size()>0);
	        
	        for(BeaconConcept concept : response) {
	        		_logger.debug("Test concept:"+concept.toString());
	        }
        } catch(Exception e) {
        	e.printStackTrace();
        }
    }
    
}
