/*
 * Translator Knowledge Beacon API
 * This is the Translator Knowledge Beacon web service application programming interface (API).  This OpenAPI (\"Swagger\") document may be used as the input specification into a tool like [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen/blob/master/README.md) to generate client and server code stubs implementing the API, in any one of several supported computer languages and frameworks. In order to customize usage to your web site, you should change the 'host' directive below to your hostname. 
 *
 * OpenAPI spec version: 1.0.11
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.api;

import java.util.ArrayList;
import java.util.List;

//import org.junit.Ignore;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import bio.knowledge.client.ApiException;
import bio.knowledge.client.model.BeaconAnnotation;
import bio.knowledge.client.model.BeaconStatement;

/**
 * API tests for StatementsApi
 */
//@Ignore
public class StatementsApiTest {
	
	private static Logger _logger = LoggerFactory.getLogger(StatementsApiTest.class);
			
    private final StatementsApi api = new StatementsApi();
    
    /**
     * 
     *
     * Given a list of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of exactly matching concepts, retrieves a paged list of concept-relations where either the subject or object concept matches at least one concept in the input list 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatementsTest() throws ApiException {
    	
		_logger.debug("getStatementsTest:");
	
        List<String> s = new ArrayList<String>();
        s.add("wd:Q18250517");
        
        String relations = null;
        List<String> t = null;
        String keywords = null;
        String types = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        
        List<BeaconStatement> response = api.getStatements(s, relations, t, keywords, types, pageNumber, pageSize);

        assert(response.size()>0);

        for(BeaconStatement statement : response) {
       		_logger.debug(statement.toString());
        }
    }
    
    /**
     * 
     *
     * Given a list of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of exactly matching concepts, retrieves a paged list of concept-relations where either the subject or object concept matches at least one concept in the input list 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEvidenceTest() throws ApiException {
    	
		_logger.debug("getEvidenceTest:");
        
        String statementId = "kbs:Q79899_P276_Q18250517";
        String keywords = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        
        List<BeaconAnnotation> response = api.getEvidence(statementId, keywords, pageNumber, pageSize);

        assert(response.size()>0);

        for(BeaconAnnotation annotation : response) {
       		_logger.debug(annotation.toString());
        }    	
    }

    
}
