/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package bio.knowledge.server.api;

import bio.knowledge.server.model.ServerPredicate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-08-20T20:17:56.260Z[GMT]")
@Api(value = "predicates", description = "the predicates API")
public interface PredicatesApi {

    PredicatesApiDelegate getDelegate();

    @ApiOperation(value = "Get supported relationships by source and target", nickname = "predicatesGet", notes = "", response = Map.class, responseContainer = "Map", tags={ "predicates", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Predicates by source and target", response = Map.class, responseContainer = "Map") })
    @RequestMapping(value = "/predicates",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Map<String, Map<String,List<String>>>> getPredicates() {
        return getDelegate().getPredicates();
    }

    @ApiOperation(value = "Details of predicates used in statements issued, by the knowledge source", notes = "", response = ServerPredicate.class, responseContainer = "List", tags={ "metadata", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Successful response with predicates with CURIE and definitions indexed by beacons which support the relation ", response = ServerPredicate.class) })
    @RequestMapping(value = "/predicates/details",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<List<ServerPredicate>> getPredicatesDetails(@ApiParam(value = "set of aggregator indices of beacons to constrain predicates returned ") @RequestParam(value = "beacons", required = false) List<Integer> beacons);

}
